name = "Hankel"
uuid = "74863788-d124-456e-a676-9b76578dd39e"
authors = ["chrisbrahms <38351086+chrisbrahms@users.noreply.github.com>"]
version = "0.5.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ChainRulesCore = "0.7, 0.8, 0.9"
SpecialFunctions = "0.10"
julia = "1"
